#!/usr/bin/env python3

from multiprocessing import RLock, parent_process
import random

"""This program plays a game of Rock, Paper, Scissors between two Players,
and reports both Player's scores each round."""

moves = ['rock', 'paper', 'scissors']

"""The Player class is the parent class for all of the Players
in this game"""


class Player:
    def move(self):
        return 'rock'

    def learn(self, my_move, their_move):
        pass


class RandomPlayer(Player):
    def move(self):
        return random.choices(moves)


class Game:
    def __init__(self, p1, p2):
        self.p1 = p1
        self.p2 = p2


    def beats(self, one, two):
        print(one)
        print(two)
        if one == 'rock' and two == 'rock':
            return "nil"
        elif one == 'rock' and two == 'paper':
            return "p2"
        elif one == 'rock' and two == 'scissors':
            return "p1"
        elif one == 'paper' and two == 'rock':
            return "p1"
        elif one == 'paper' and two == 'paper':
            return "nil"
        elif one == 'paper' and two == 'scissors':
            return "p2"
        elif one == 'scissors' and two == 'rock':
            return "p2"
        elif one == 'scissors' and two == 'paper':
            return "p1"
        elif one == 'scissors' and two == 'scissors':
            return "nil"


    def play_round(self):
        move1 = self.p1.move()
        move2 = self.p2.move()
        print(f"Player 1: {move1}  Player 2: {move2}")
        score =  self.beats(move1, move2)
        print(score)  
        self.p1.learn(move1, move2)
        self.p2.learn(move2, move1)

    def play_game(self):
        print("Game start!")
        for round in range(3):
            print(f"Round {round}:")
            self.play_round()
        print("Game over!")


if __name__ == '__main__':
    game = Game(RandomPlayer(), RandomPlayer())
    game.play_game()
